name: Go-diff
description: Action that returns a JSON containing an array of modified files and an array of modified directories.

inputs:
  head_branch:
    description: "Head branch for comparison. Only alphanumeric, dash and underscores are accepted."
    required: true
    default: dev
  base_branch:
    description: "Base branch for comparison. Only alphanumeric, dash and underscores are accepted."
    required: true
    default: main

outputs:
  modified_output:
    description: "JSON containing ModifiedFiles (array containing modified files), ModifiedDirs (array containing modified directories) and ModifiedProjects (array containing modified directories at root level)"

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.head_branch }}
    - ${{ inputs.base_branch }}