name: Go-diff
description: Action that returns a JSON containing an array of modified files and an array of modified directories.

inputs:
  head_branch:
    description: "Head branch for comparison. Only alphanumeric, dash and underscores are accepted."
    required: true
    default: dev
  base_branch:
    description: "Base branch for comparison. Only alphanumeric, dash and underscores are accepted."
    required: true
    default: main

outputs:
  modified_output:
    description: "JSON containing ModifiedFiles (array containing modified files), ModifiedDirs (array containing modified directories) and ModifiedProjects (array containing modified directories at root level)"
    value: ${{ steps.go_diff.outputs.modified }}

runs:
  using: "composite"
  steps:
    - name: Execute Go-diff
      id: go_diff
      run: |
        wget -o- https://github.com/noh4nsen/go-diff/releases/download/0.3.0/go-diff-0.3.0
        export output=$(./build/go-diff-0.3.0 ${{ inputs.head_branch }} ${{ inputs.base_branch }})
        if [[ -z "$output" ]]; then
          exit 0
        fi
        echo "modified=output" >> GITHUB_OUTPUT
      shell: bash
