name: Build go-diff

on: [workflow_dispatch, push]
permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                go-version: '1.20'
            
            - name: Build
              run: |
                cd src
                make clean
                make build

            - name: Commit Artifacts
              run: |
                git config --global user.name "noh4nsen"
                git config --global user.email "noh4nsen@gmail.com"
                git commit -am "Chore: build workflow updated compiled binaries"
                git push