name: Build go-diff

on:
    push:
        branches:
            - release/**
permissions:
    contents: write

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.20'
        - name: Build
          run: |
            cd src
            make clean
            make build
        - name: Config git
          run: |
            git config --global user.name "noh4nsen"
            git config --global user.email "noh4nsen@gmail.com"
        - name: Commit Artifacts
          run: |
            git add .
            git commit -am "Chore: build workflow updated compiled binaries"
            git push
        - name: Git tag
          run: |
            export version=$(git branch --show-current | sed 's:.*/::')
            git tag -a $version -m $version
            git push origin --tags
        - name: Generate Changelog
          run: |
            docker run -v "$PWD":/workdir quay.io/git-chglog/git-chglog:latest -o CHANGELOG.md
            git add .
            git commit -am "Chore: generate changelog"
            git push
