name: Build go-diff

on: 
    push:
        branches:
            - release/**
permissions:
    contents: write

jobs:
    setup:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.20'
    build:
      runs-on: ubuntu-latest
      needs: [setup]
      steps:           
        - name: Build
          run: |
            cd src
            make clean
            make build

    commit-and-tag:
      runs-on: ubuntu-latest
      needs: [setup, build]
      steps:
        - name: Commit Artifacts
          run: |
            git config --global user.name "noh4nsen"
            git config --global user.email "noh4nsen@gmail.com"
            git commit -am "Chore: build workflow updated compiled binaries"
            git push
        - name: Git tag
          run: |
            export version=$(git branch --show-current | sed 's:.*/::')
            git tag -a $version -m $version
            git push origin --tags