name: Usage example

on: [workflow_dispatch]

jobs:
    diff:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Test Go-diff
            id: test-go-diff
            uses: noh4nsen/go-diff@75547ee7ffc300ac3dd1f73785cf929a0c48f664
            with:
              head_branch: dev
              base_branch: main
          - name: Print output
            run: |
              echo ${{ steps.test-go-diff.outputs.modified_files }}
              echo ${{ steps.test-go-diff.outputs.modified_dirs }}
              echo ${{ steps.test-go-diff.outputs.modified_projects }}